apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rocketchat
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /rocketchat
            pathType: Prefix
            backend:
              service:
                name:  rocketchat-server
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: rocketchat-default
 namespace: default
spec:
  defaultBackend:
    service:
      name: rocketchat-server
      port:
        number: 80
