apiVersion: v1
kind: Service
metadata:
  name: rocketmongo
  labels:
    app: rocketmongo
spec:
  selector:
    app: rocketmongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: rocketchat-server
spec:
  selector:
    app: rocketchat-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000
